# Generated by Django 6.0.1 on 2026-01-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('unit_type', models.CharField(choices=[('count', 'By Item'), ('weight', 'By Weight')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.CharField(choices=[('kg', 'kilograms'), ('lb', 'pounds'), ('g', 'grams'), ('oz', 'ounces'), ('l', 'liters'), ('ml', 'milliliters'), ('fl oz', 'fluid ounces')], max_length=10)),
            ],
        ),
    ]
